"""Data deep-dive for the PUCAR hackathon dataset.

Reads the six CSVs in data/pucar/ and writes docs/DATA_PROFILE.md.
Run:  .venv/bin/python scripts/data_profile.py
"""
from __future__ import annotations

import re
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
from core.pucar_engine import default_data_dir  # noqa: E402

DATA = default_data_dir()  # the organisers' data/ when inside their repo, else data/pucar/
OUT = ROOT / "docs" / "DATA_PROFILE.md"
AS_OF = pd.Timestamp("2026-09-24")
DAY_A, DAY_B = 330, 420  # 10:30-12:30 + 13:30-17:00 = 330; 420 = a 7-hour sitting

roster = pd.read_csv(DATA / "roster_sample_100.csv")
cal = pd.read_csv(DATA / "court_calendar.csv")
ref = pd.read_csv(DATA / "hearing_type_reference.csv")
fail = pd.read_csv(DATA / "hearing_failure_reasons.csv")
subst = pd.read_csv(DATA / "substantiveness_by_hearing_type.csv")
cl = pd.read_csv(DATA / "sample_causelist_2026-09-22.csv")

MAIN_FLOW = [
    "ADMISSION", "DELAY_CONDONATION_HEARING", "COGNIZANCE", "APPEARANCE", "WARRANT",
    "PLEA", "EXAMINATION_UNDER_S351_BNSS", "EVIDENCE_COMPLAINANT", "EVIDENCE_ACCUSED",
    "ARGUMENTS", "JUDGEMENT",
]
SIDE = ["BAIL", "REPORTS", "APPLICATION_REVIEW"]
ALL_TYPES = MAIN_FLOW + SIDE


def key(label: str) -> str:
    """'Examination Under S351 Bnss' -> 'EXAMINATION_UNDER_S351_BNSS'."""
    return re.sub(r"\W+", "_", str(label).strip()).upper()


def md(df: pd.DataFrame, index: bool = False, floatfmt: str = ".2f") -> str:
    return df.to_markdown(index=index, floatfmt=floatfmt)


def pct(x: float) -> str:
    return f"{100 * x:.1f}%"


def col_table(df: pd.DataFrame, meanings: dict[str, str]) -> str:
    rows = []
    for c in df.columns:
        s = df[c]
        if pd.api.types.is_numeric_dtype(s):
            stat = f"min {s.min():g}, median {s.median():g}, mean {s.mean():.2f}, max {s.max():g}"
        else:
            vc = s.value_counts()
            top = ", ".join(f"{str(k)[:28]} ({v})" for k, v in vc.head(3).items())
            stat = f"{s.nunique()} unique, {s.isna().sum()} null; top: {top}"
        rows.append({"column": c, "dtype": str(s.dtype), "meaning": meanings.get(c, ""), "key stats": stat})
    return md(pd.DataFrame(rows))


out: list[str] = []
w = out.append

w("# PUCAR dataset: data profile\n")
w(f"Generated by `scripts/data_profile.py` from `data/pucar/` (as-of date {AS_OF.date()}). "
  "Anonymised cheque-dishonour complaints (NI Act s.138) in a Kerala magistrate court under BNSS 2023. "
  "Every number below is recomputed on each run.\n")
w("Lifecycle the data implies: Admission -> Delay Condonation Hearing (only if the complaint is late) -> "
  "Cognizance -> Appearance (loops through Warrant when summons are not served or the accused is absent) -> "
  "Plea -> Examination u/s 351 BNSS -> Evidence Complainant -> Evidence Accused -> Arguments -> Judgement. "
  "Side purposes: Bail, Reports (mediation reports), Application Review.\n")

# ---------------------------------------------------------------- files
w("## Part A. File by file\n")

# roster
hcols = [c for c in roster.columns if c.startswith("hearings_")]
roster_meanings = {
    "case_number": "Court's case number after cognizance (ST = summary trial), e.g. ST/819/2023",
    "filing_number": "E-filing number assigned at filing (KL-serial-year)",
    "filing_date": "Date the complaint was filed (string, YYYY-MM-DD)",
    "advocate_id": "Anonymised complainant's advocate",
    "party_id": "Anonymised party (complainant) id",
    "current_stage": "Stage the case is in now",
    "last_hearing_summary": "Free text: 'Present: ...', 'Absent: ...', then the order note of the last hearing",
    "purpose_of_next_hearing": "What the next listed hearing is for (can differ from current_stage)",
    "total_hearings_held": "Sum of all hearings_* columns",
}
for c in hcols:
    roster_meanings[c] = f"Hearings held so far with purpose {c.replace('hearings_', '').replace('_', ' ').title()}"
w("### 1. roster_sample_100.csv\n")
w(f"**Purpose:** the docket to schedule against, one row per case. **Rows:** {len(roster)}; **columns:** {roster.shape[1]}.\n")
w(col_table(roster, roster_meanings) + "\n")

# calendar
w("### 2. court_calendar.csv\n")
w(f"**Purpose:** which days the court sits. **Rows:** {len(cal)} ({cal.date.min()} to {cal.date.max()}).\n")
w(col_table(cal, {
    "date": "Calendar date", "day_of_week": "Weekday name",
    "is_weekly_off": "Yes on Saturdays/Sundays (weekly off)", "is_holiday": "Yes on a gazetted court holiday",
    "holiday_name": "Name of the holiday (blank otherwise)", "is_working_day": "Yes when the court sits",
}) + "\n")

# reference
w("### 3. hearing_type_reference.csv\n")
w(f"**Purpose:** per hearing type, how many hearings a case needs, how long each takes, and the usual gap to the next date. **Rows:** {len(ref)}.\n")
w(col_table(ref, {
    "Hearing Purpose": "Hearing type (14)",
    "Min Hearings per Case": "Fewest hearings of this type a case needed",
    "Max Hearings per Case": "Most hearings of this type a case needed",
    "Mean Hearings per Case": "Average hearings of this type per case that reaches it",
    "Median Hearings per Case": "Median of the same",
    "Time it takes for hearing (mins) - estimated": "Judge minutes per hearing (estimate)",
    "Time to next hearing given this is the purpose (days)": "Usual adjournment gap in days",
}) + "\n")

# failure
w("### 4. hearing_failure_reasons.csv\n")
w(f"**Purpose:** per hearing type, counts of why a hearing did not move the case forward. **Rows:** {len(fail)}.\n")
REASONS = [c for c in fail.columns if c not in ("hearingType", "total_no", "source")]
fm = {"hearingType": "Hearing type", "total_no": "Total non-substantive hearings observed (sum of reason columns)",
      "source": "'real' (observed) or 'estimated - <reasoning>'"}
for c in REASONS:
    fm[c] = f"Count of failed hearings attributed to: {c}"
w(col_table(fail, fm) + "\n")
chk = (fail[REASONS].sum(axis=1) == fail.total_no)
w(f"Reason columns sum to `total_no` in {chk.sum()} of {len(fail)} rows. "
  f"Real rows: {(fail.source == 'real').sum()}, estimated: {(fail.source != 'real').sum()}.\n")

# substantiveness
w("### 5. substantiveness_by_hearing_type.csv\n")
w(f"**Purpose:** probability a hearing of each type is substantive (moves the case). **Rows:** {len(subst)}.\n")
w(col_table(subst, {
    "hearingType": "Hearing type",
    "Substantive Hearings (percentage probability)": "Percent of hearings of this type that moved the case forward",
    "source": "'real' or 'estimated - <reasoning>'",
}) + "\n")

# causelist
w("### 6. sample_causelist_2026-09-22.csv\n")
w(f"**Purpose:** the shape of one real day's cause list. **Rows:** {len(cl)}.\n")
w(col_table(cl, {
    "Case Number": "Case number (ST/n/yyyy)", "Filing Number": "E-filing number",
    "Hearing Type": "Purpose of the listing", "Hearing Date": "The listed date",
}) + "\n")
in_roster = cl["Case Number"].isin(roster.case_number).sum()
w(f"Case numbers in this list that also appear in the roster: {in_roster} of {len(cl)} "
  "(the list is a shape reference, not a slice of the roster).\n")

# ---------------------------------------------------------------- cross-file
w("## Part B. Analysis\n")

# 1. roster -----------------------------------------------------------
w("### B1. Roster\n")
roster["filing_dt"] = pd.to_datetime(roster.filing_date)
roster["age_years"] = (AS_OF - roster.filing_dt).dt.days / 365.25
age = roster.age_years
bins = [0, 1, 2, 3, 4, 5, 20]
labels = ["<1", "1-2", "2-3", "3-4", "4-5", "5+"]
age_tab = pd.cut(age, bins, labels=labels, right=False).value_counts().reindex(labels).rename("cases").to_frame()
n4, n5 = int((age >= 4).sum()), int((age >= 5).sum())
w(f"**Age** (years since filing, as of {AS_OF.date()}): median {age.median():.2f}, mean {age.mean():.2f}, "
  f"oldest {age.max():.1f} (filed {roster.filing_date.min()}), newest filed {roster.filing_date.max()}. "
  f"**4+ years: {n4} cases; 5+ years: {n5} cases.**\n")
w(md(age_tab, index=True) + "\n")

stage_order = [s.replace("_", " ").title().replace("S351 Bnss", "S351 Bnss") for s in ALL_TYPES]
cs = roster.current_stage.value_counts().rename("cases").to_frame()
pn = roster.purpose_of_next_hearing.value_counts().rename("cases").to_frame()
w("**current_stage counts**\n")
w(md(cs, index=True) + "\n")
w("**purpose_of_next_hearing counts**\n")
w(md(pn, index=True) + "\n")
same = (roster.current_stage == roster.purpose_of_next_hearing).sum()
w(f"Next purpose equals current stage in {same} cases; {len(roster) - same} cases are listed next for a different purpose "
  "(side purposes, a step forward, or a step back to Warrant).\n")
xt = pd.crosstab(roster.current_stage, roster.purpose_of_next_hearing)
xt.columns = [c.replace("Examination Under S351 Bnss", "S351").replace("Delay Condonation Hearing", "DelayCond")
              .replace("Evidence Complainant", "EvidC").replace("Evidence Accused", "EvidA")
              .replace("Application Review", "AppRev") for c in xt.columns]
w("**current_stage (rows) x purpose_of_next_hearing (columns)** (S351 = Examination u/s 351, DelayCond = Delay Condonation, EvidC/EvidA = Evidence Complainant/Accused, AppRev = Application Review)\n")
w(md(xt, index=True) + "\n")

hp = pd.DataFrame({
    "mean": roster[hcols].mean(), "median": roster[hcols].median(), "max": roster[hcols].max(),
    "share of cases >0": (roster[hcols] > 0).mean().map(pct),
    "mean where >0": roster[hcols].where(roster[hcols] > 0).mean(),
})
hp.index = [c.replace("hearings_", "") for c in hp.index]
w("**Hearings held per stage (all 100 cases)**\n")
w(md(hp, index=True) + "\n")
w(f"Total hearings held: sum {roster.total_hearings_held.sum()}, mean {roster.total_hearings_held.mean():.1f}, "
  f"median {roster.total_hearings_held.median():.0f}, max {roster.total_hearings_held.max()}. "
  f"Row sums match `total_hearings_held` in {(roster[hcols].sum(axis=1) == roster.total_hearings_held).sum()} of 100 rows.\n")
th = roster.groupby("current_stage").agg(cases=("case_number", "size"),
                                          median_total_hearings=("total_hearings_held", "median"),
                                          median_age_years=("age_years", "median"))
th = th.sort_values("median_total_hearings")
w("**Total hearings held by current stage**\n")
w(md(th, index=True, floatfmt=".1f") + "\n")

adv = roster.advocate_id.value_counts()
dist = adv.value_counts().sort_index().rename("advocates").to_frame()
dist.index.name = "cases per advocate"
multi = adv[adv >= 2]
w(f"**Advocates:** {adv.size} distinct across 100 cases; max {adv.max()} cases for one advocate ({adv.idxmax()}). "
  f"**{len(multi)} advocates have 2+ cases, covering {multi.sum()} cases** -> clustering opportunity "
  "(list an advocate's matters on the same day, back to back).\n")
w(md(dist, index=True) + "\n")
w(f"**party_id:** {roster.party_id.nunique()} unique of {len(roster)} (every case has its own party; no party clustering possible). "
  f"case_number unique: {roster.case_number.is_unique}; filing_number unique: {roster.filing_number.is_unique}.\n")

# 2. last_hearing_summary --------------------------------------------
w("### B2. Parsing last_hearing_summary\n")
ROLES = ["Complainant", "Complainant's Advocate", "Accused", "Accused Advocate"]


def parse(text: str) -> dict:
    lines = str(text).split("\n")
    present, absent, order = [], [], []
    for ln in lines:
        if ln.startswith("Present:"):
            present = [x.strip() for x in ln[8:].split(",") if x.strip()]
        elif ln.startswith("Absent:"):
            absent = [x.strip() for x in ln[7:].split(",") if x.strip()]
        else:
            order.append(ln)
    return {"present": present, "absent": absent, "order": " ".join(order).strip()}


parsed = roster.last_hearing_summary.map(parse)
roster["order_note"] = parsed.map(lambda d: d["order"])
pa = pd.DataFrame({
    "present": [sum(r in d["present"] for d in parsed) for r in ROLES],
    "absent": [sum(r in d["absent"] for d in parsed) for r in ROLES],
}, index=ROLES)
pa["absent share"] = (pa.absent / len(roster)).map(pct)
w(md(pa, index=True) + "\n")
all_abs = sum(len(d["present"]) == 0 for d in parsed)
only_cadv = sum(d["present"] == ["Complainant's Advocate"] for d in parsed)
w(f"Nobody present: {all_abs} cases. Only the complainant's advocate present: {only_cadv} cases. "
  "The accused is the party most often missing, which is what drives the Appearance/Warrant loop.\n")

CATS = [
    ("judgment pronounced", r"judgment pronounced|convicted|acquitted"),
    ("jurisdiction enquiry s.225", r"225"),
    ("mediation", r"mediation"),
    ("evidence recorded", r"examined|exhibits marked|proof affidavit"),
    ("heard / for judgment", r"\bheard\b|for judgment"),
    ("party absent / last chance", r"absent|last chance|shall be present"),
    ("process pending", r"summons|warrant|\bnbw\b|notice|take steps|return of"),
    ("not ready / time sought / objections", r"not ready|time|objection|adjourn"),
]


def classify(note: str) -> str:
    n = note.lower()
    for name, pat in CATS:
        if name == "process pending" and re.search(r"\bserved\b", n) and "return of" not in n:
            continue  # "summons served" / "notice served": process is done, not pending
        if re.search(pat, n):
            return name
    return "other"


roster["order_cat"] = roster.order_note.map(classify)
cat_order = [c for c, _ in CATS] + ["other"]
rows = []
for c in cat_order:
    sub = roster[roster.order_cat == c]
    ex = sub.order_note.iloc[0] if len(sub) else ""
    ex = ex if len(ex) <= 140 else ex[:137] + "..."
    rows.append({"category": c, "cases": len(sub), "example": ex})
w("Final order line classified by keyword (first match wins, in the order listed; "
  "'served' without 'return of' is not counted as process pending):\n")
w(md(pd.DataFrame(rows)) + "\n")
jp = roster[roster.order_cat == "judgment pronounced"].order_note.str.lower()
w(f"Of the judgments pronounced: convicted {jp.str.contains('convicted').sum()}, "
  f"acquitted {jp.str.contains('acquitted').sum()}.\n")
w("**Order category by next purpose**\n")
w(md(pd.crosstab(roster.order_cat, roster.purpose_of_next_hearing).loc[lambda d: d.sum(axis=1) > 0], index=True) + "\n")

# 3. reference + lifecycle -----------------------------------------
w("### B3. Hearing-type reference and full-lifecycle cost\n")
R = ref.rename(columns={
    "Hearing Purpose": "type", "Min Hearings per Case": "min", "Max Hearings per Case": "max",
    "Mean Hearings per Case": "mean", "Median Hearings per Case": "median",
    "Time it takes for hearing (mins) - estimated": "minutes",
    "Time to next hearing given this is the purpose (days)": "gap_days",
}).set_index("type")
R["judge min / case (mean x minutes)"] = R["mean"] * R.minutes
R["calendar days / case (mean x gap)"] = R["mean"] * R.gap_days
w(md(R[["minutes", "gap_days", "mean", "median", "max", "judge min / case (mean x minutes)",
        "calendar days / case (mean x gap)"]], index=True) + "\n")


def lifecycle(types: list[str]) -> tuple[float, float, float, float]:
    r = R.loc[types]
    return (r["mean"].sum(), (r["mean"] * r.minutes).sum(), (r["mean"] * r.gap_days).sum(), r["mean"].sum() * 60)


scen = {
    "Full main flow (with Delay Condonation and Warrant)": MAIN_FLOW,
    "On-time complaint, accused appears (no Delay Condonation, no Warrant)":
        [t for t in MAIN_FLOW if t not in ("DELAY_CONDONATION_HEARING", "WARRANT")],
    "On-time complaint, Warrant loop needed": [t for t in MAIN_FLOW if t != "DELAY_CONDONATION_HEARING"],
}
lrows = []
for name, types in scen.items():
    h, m, d_ref, d60 = lifecycle(types)
    lrows.append({"scenario": name, "hearings": h, "judge minutes": m,
                  "calendar days (reference gaps)": d_ref, "years (ref)": d_ref / 365.25,
                  "calendar days (flat 60-day gap)": d60, "years (60d)": d60 / 365.25})
LC = pd.DataFrame(lrows)
w("Expected cost of one case's lifecycle = sum over stages of mean hearings x minutes (judge time) "
  "and mean hearings x gap (elapsed days; this ignores listing delay beyond the gap and assumes stages run one after another):\n")
w(md(LC, floatfmt=".1f") + "\n")
full_h, full_m, full_dref, full_d60 = lifecycle(MAIN_FLOW)
ev_share = (R.loc[["EVIDENCE_COMPLAINANT", "EVIDENCE_ACCUSED"], "judge min / case (mean x minutes)"].sum()
            / R.loc[MAIN_FLOW, "judge min / case (mean x minutes)"].sum())
w(f"Evidence (complainant + accused) is {pct(ev_share)} of the full-flow judge minutes. "
  "The reference gaps assume the case is re-listed on the usual gap every time; the flat 60-day gap is a stress case for a crowded list. "
  f"At the reference gaps a full case would take {full_dref / 365.25:.1f} years, at 60 days {full_d60 / 365.25:.1f} years.\n")

# 4. substantiveness + failure --------------------------------------
w("### B4. Substantiveness and failure reasons\n")
GROUPS = {
    "process": ["Awaiting Process / Summons / Warrant Return"],
    "absence": ["Respondent Absence / Non-Compliance", "Petitioner Absence / Non-Compliance", "Both Parties Unready / Absent"],
    "unready": ["Party Sought Time / Adjournment", "Evidence / Filing Not Ready"],
    "court": ["Court Administrative Issue", "Court Holiday / No Sitting", "External Dependency"],
    "unclear": ["Unclear"],
}
F = fail.set_index("hearingType")
S = subst.set_index("hearingType")
T = pd.DataFrame(index=ALL_TYPES)
T["p_substantive %"] = S["Substantive Hearings (percentage probability)"]
T["p source"] = S.source.map(lambda s: "real" if s == "real" else "estimated")
T["failures"] = F.total_no
for g, cols in GROUPS.items():
    T[g] = F[cols].sum(axis=1)
    T[g + " %"] = (T[g] / T.failures * 100).round(0)
T["fail source"] = F.source.map(lambda s: "real" if s == "real" else "estimated")
T["top group"] = T[list(GROUPS)].idxmax(axis=1)
w("Groups: process = Awaiting Process/Summons/Warrant Return; absence = Respondent, Petitioner, Both Parties Unready/Absent; "
  "unready = Party Sought Time, Evidence/Filing Not Ready; court = Court Administrative, Court Holiday, External Dependency; unclear.\n")
w(md(T[["p_substantive %", "p source", "failures", "process", "absence", "unready", "court", "unclear",
        "top group", "fail source"]], index=True, floatfmt=".1f") + "\n")
w("**Failure mix as % of each type's failures**\n")
w(md(T[[g + " %" for g in GROUPS]], index=True, floatfmt=".0f") + "\n")

tot_fail = int(F.total_no.sum())
real_fail = int(F[F.source == "real"].total_no.sum())
G = pd.DataFrame({"failures": {g: int(F[c].sum().sum()) for g, c in GROUPS.items()}})
G["share"] = (G.failures / tot_fail).map(pct)
G["of which real rows"] = {g: int(F[F.source == "real"][c].sum().sum()) for g, c in GROUPS.items()}
G = G.sort_values("failures", ascending=False)
w(f"**Overall failure pools** ({tot_fail} failed hearings; {real_fail} from real rows)\n")
w(md(G, index=True) + "\n")
cells = []
for t in ALL_TYPES:
    for g, cols in GROUPS.items():
        if g == "unclear":
            continue
        cells.append({"hearing type": t, "group": g, "failures": int(F.loc[t, cols].sum()),
                      "source": T.loc[t, "fail source"]})
P = pd.DataFrame(cells).sort_values("failures", ascending=False).head(10).reset_index(drop=True)
P.index += 1
P["share of all failures"] = (P.failures / tot_fail).map(pct)
w("**Top 10 preventable pools (hearing type x group, count-weighted; 'court' is only partly preventable)**\n")
w(md(P, index=True) + "\n")
ext = int(F["External Dependency"].sum())
w(f"'External Dependency' ({ext} failures) sits almost entirely in Warrant ({F.loc['WARRANT', 'External Dependency']}, police execution) "
  f"and Reports ({F.loc['REPORTS', 'External Dependency']}, mediation centre reports), so it is preventable by chasing the outside agency, not by the judge.\n")

# 5. calendar --------------------------------------------------------
w("### B5. Court calendar\n")
cal["dt"] = pd.to_datetime(cal.date)
cal["month"] = cal.dt.dt.strftime("%Y-%m")
CM = cal.groupby("month").agg(days=("date", "size"),
                              working=("is_working_day", lambda s: (s == "Yes").sum()),
                              weekly_off=("is_weekly_off", lambda s: (s == "Yes").sum()),
                              holidays=("is_holiday", lambda s: (s == "Yes").sum()))
w(md(CM, index=True) + "\n")
offs = cal[cal.is_weekly_off == "Yes"].day_of_week.value_counts()
w(f"Weekly offs fall on: {', '.join(f'{k} ({v})' for k, v in offs.items())}.\n")
H = cal[cal.is_holiday == "Yes"][["date", "day_of_week", "holiday_name", "is_weekly_off"]]
w("**Holidays**\n")
w(md(H) + "\n")
q4 = cal[(cal.dt >= "2026-10-01") & (cal.dt <= "2026-12-31") & (cal.is_working_day == "Yes")]
w(f"**Working days 2026-10-01 to 2026-12-31: {len(q4)}** "
  f"(= {len(q4) * DAY_A:,} judge minutes at {DAY_A} min/day, {len(q4) * DAY_B:,} at {DAY_B}). "
  f"Calendar working days in the whole file: {(cal.is_working_day == 'Yes').sum()} of {len(cal)}. "
  "Note the holiday names (Samvatsari, Diwali New Year) appear to follow a Gujarat-style list, not Kerala's; "
  "Kerala court holidays such as Onam would differ.\n")

# 6. causelist -------------------------------------------------------
w("### B6. Sample cause list (2026-09-22)\n")
mix = cl["Hearing Type"].value_counts().rename("listed").to_frame()
mix["share"] = (mix.listed / len(cl)).map(pct)
rp = roster.purpose_of_next_hearing.map(key).value_counts()
cmp_ = pd.DataFrame(index=ALL_TYPES)
cmp_["causelist %"] = (cl["Hearing Type"].value_counts() / len(cl) * 100).reindex(ALL_TYPES).fillna(0)
cmp_["roster next purpose %"] = (rp / len(roster) * 100).reindex(ALL_TYPES).fillna(0)
cmp_["difference (pp)"] = cmp_["causelist %"] - cmp_["roster next purpose %"]
w(f"**{len(cl)} matters listed on one day** ({cl['Hearing Date'].nunique()} date in file).\n")
w(md(cmp_, index=True, floatfmt=".1f") + "\n")
tvd = cmp_[["causelist %", "roster next purpose %"]].diff(axis=1).iloc[:, 1].abs().sum() / 2
w(f"Total variation distance between the two mixes: {tvd:.1f} pp. The real day is dominated by early-stage "
  f"Appearance ({cmp_.loc['APPEARANCE', 'causelist %']:.0f}%) while the roster's next purposes lean late-stage "
  "(Evidence Accused, Judgement, Application Review). A roster-driven cause list will look heavier and later than a real one.\n")

L = cl["Hearing Type"].value_counts().rename("listed").to_frame()
L["minutes each"] = R.minutes.reindex(L.index)
L["minutes if all heard"] = L.listed * L["minutes each"]
L["p_substantive"] = S["Substantive Hearings (percentage probability)"].reindex(L.index) / 100
L["expected substantive"] = L.listed * L.p_substantive
L["expected minutes (substantive only)"] = L["expected substantive"] * L["minutes each"]
w(md(L, index=True) + "\n")
need = L["minutes if all heard"].sum()
exp_sub = L["expected substantive"].sum()
exp_min = L["expected minutes (substantive only)"].sum()
w(f"- Minutes needed if every listed matter were heard at reference minutes: **{need:.0f}**, "
  f"i.e. {need / DAY_A:.2f}x a {DAY_A}-minute day and {need / DAY_B:.2f}x a {DAY_B}-minute day.\n"
  f"- Expected substantive hearings using p_substantive: **{exp_sub:.1f} of {len(cl)}** ({pct(exp_sub / len(cl))}); "
  f"{len(cl) - exp_sub:.1f} expected adjournments.\n"
  f"- Minutes those substantive hearings need: {exp_min:.0f} ({pct(exp_min / DAY_A)} of {DAY_A}, {pct(exp_min / DAY_B)} of {DAY_B}). "
  "Even the expected substantive load alone exceeds a 330-minute day, before any time for calling and adjourning "
  "the other matters; the list is sized on the expectation that most will not go ahead.\n")

# 7. registry checklist ---------------------------------------------
w("### B7. What the registry checks before admission (NI Act s.138)\n")
w("Legal checklist; each line maps to the hearing types and failure reasons in this data that a check at filing would prevent.\n")


def ht(t: str) -> str:
    return (f"{t.replace('_', ' ').title()}: mean {R.loc[t, 'mean']:.2f} hearings/case, "
            f"{S.loc[t, 'Substantive Hearings (percentage probability)']:.1f}% substantive")


aw = "Awaiting Process / Summons / Warrant Return"
checks = [
    ("Cheque presented within 3 months of its date (validity period)",
     "Stale cheque = no offence; caught late it becomes a dismissal after full trial.",
     f"Admission ({ht('ADMISSION')}); Evidence/Filing Not Ready at Admission ({F.loc['ADMISSION', 'Evidence / Filing Not Ready']})."),
    ("Bank dishonour memo (return memo) attached",
     "Proves dishonour and the date of intimation that starts the notice clock.",
     f"Admission Evidence/Filing Not Ready ({F.loc['ADMISSION', 'Evidence / Filing Not Ready']}); Evidence Complainant Evidence/Filing Not Ready ({F.loc['EVIDENCE_COMPLAINANT', 'Evidence / Filing Not Ready']})."),
    ("Demand notice sent within 30 days of dishonour intimation (s.138(b)), with postal proof",
     "Missing or late notice defeats the complaint.",
     "Admission; later a defence point argued in Evidence Accused / Arguments."),
    ("15 days allowed to pay after notice received (s.138(c))",
     "Complaint filed before the 15 days expire is premature.",
     "Admission; Delay/limitation arithmetic starts from day 16."),
    ("Complaint within 1 month of cause of action (s.142(1)(b)); otherwise a delay condonation petition with reasons",
     "The single biggest filing-stage loop in the data.",
     f"{ht('DELAY_CONDONATION_HEARING')}; {F.loc['DELAY_CONDONATION_HEARING', 'total_no']} failed hearings. "
     f"{(roster.hearings_delay_condonation_hearing > 0).sum()} roster cases went through it."),
    ("Territorial jurisdiction (s.142(2)): court where the payee's bank branch is",
     "Wrong court means return of complaint and refiling.",
     "Admission; Application Review ('Produce the order of the Hon'ble District Court' notes)."),
    ("Proof affidavit of the complainant (s.145)",
     "Lets chief examination be on affidavit, so evidence is not re-listed for it.",
     f"{ht('EVIDENCE_COMPLAINANT')}; Evidence/Filing Not Ready {F.loc['EVIDENCE_COMPLAINANT', 'Evidence / Filing Not Ready']}, Petitioner Absence {F.loc['EVIDENCE_COMPLAINANT', 'Petitioner Absence / Non-Compliance']}."),
    ("s.141 averments when the drawer is a company (who was in charge of and responsible for the business)",
     "Missing averments get directors discharged later.",
     "Admission; Arguments / Judgement (acquittal risk)."),
    ("Accused residing beyond jurisdiction: enquiry under BNSS s.225 before summons (s.225 affidavit)",
     "Without the affidavit ready, cognizance waits.",
     f"{ht('COGNIZANCE')}; Awaiting Process at Cognizance {F.loc['COGNIZANCE', aw]} (estimated row); "
     f"{(roster.order_cat == 'jurisdiction enquiry s.225').sum()} roster order notes are s.225 enquiries."),
    ("Process fee paid, copies for each accused, full address, phone and email of the accused (BNSS allows electronic summons)",
     "Unserved summons are why cases loop Appearance -> Warrant.",
     f"Awaiting Process: Appearance {F.loc['APPEARANCE', aw]}, Warrant {F.loc['WARRANT', aw]}, Admission {F.loc['ADMISSION', aw]} "
     f"= {int(F[aw].sum())} of {tot_fail} failures ({pct(F[aw].sum() / tot_fail)}); {ht('WARRANT')}."),
]
w(md(pd.DataFrame(checks, columns=["check", "why it matters", "what it prevents in this data"])) + "\n")

# ---------------------------------------------------------------- key findings
w("## Key findings\n")
proc = int(F[GROUPS["process"]].sum().sum())
absn = int(F[GROUPS["absence"]].sum().sum())
top_adv_cases = multi.sum()
acc_abs = pa.loc["Accused", "absent"]
kf = [
    f"The backlog is old: median case age {age.median():.1f} years; {n4} of 100 cases are 4+ years old and {n5} are 5+.",
    f"Cases have already had {roster.total_hearings_held.sum()} hearings between them (median {roster.total_hearings_held.median():.0f}, max {roster.total_hearings_held.max()}); "
    f"{cs.loc['Evidence Complainant', 'cases'] + cs.loc['Evidence Accused', 'cases']} sit in evidence and {cs.loc['Judgement', 'cases']} are at Judgement.",
    f"Late filing is the norm, not the exception: {(roster.hearings_delay_condonation_hearing > 0).sum()} of 100 roster cases had at least one Delay Condonation hearing "
    f"(mean {roster.hearings_delay_condonation_hearing.mean():.2f} per case).",
    f"Process is the largest failure pool: {proc} of {tot_fail} failed hearings ({pct(proc / tot_fail)}) are Awaiting Process/Summons/Warrant Return, "
    f"{F.loc['WARRANT', aw]} of them in Warrant alone (Warrant is only {S.loc['WARRANT', 'Substantive Hearings (percentage probability)']:.1f}% substantive).",
    f"Absence is second: {absn} failures ({pct(absn / tot_fail)}). In the last hearing the accused was absent in {acc_abs} of 100 cases.",
    f"A full main-flow case costs about {full_m:.0f} judge minutes over {full_h:.1f} hearings; at reference gaps that is {full_dref / 365.25:.1f} years elapsed, "
    f"at a flat 60-day gap {full_d60 / 365.25:.1f} years. Evidence is {pct(ev_share)} of the minutes.",
    f"The 2026-09-22 list had {len(cl)} matters needing {need:.0f} minutes if all were heard ({need / DAY_A:.2f}x a {DAY_A}-minute day), "
    f"but only {exp_sub:.1f} are expected to be substantive, needing {exp_min:.0f} minutes. Q4 2026 has {len(q4)} working days ({len(q4) * DAY_A:,} judge minutes).",
    f"The real day is {cmp_.loc['APPEARANCE', 'causelist %']:.0f}% Appearance; the roster's next purposes are only {cmp_.loc['APPEARANCE', 'roster next purpose %']:.0f}% Appearance "
    f"(TVD {tvd:.0f} pp), so roster-based lists will skew late-stage.",
    f"{len(multi)} of {adv.size} advocates hold 2+ cases ({top_adv_cases} cases; max {adv.max()}): same-day clustering is available. "
    "Every party_id is unique, so there is no party clustering.",
    f"Filing-stage checks target real loops: Delay Condonation averages {R.loc['DELAY_CONDONATION_HEARING', 'mean']:.2f} hearings/case at "
    f"{S.loc['DELAY_CONDONATION_HEARING', 'Substantive Hearings (percentage probability)']:.1f}% substantive, and complete accused addresses/phone/email "
    f"attack the {int(F[aw].sum())} Awaiting Process failures.",
]
for k in kf:
    w(f"- {k}")
w("")

OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text("\n".join(out))
print(f"wrote {OUT} ({len(out)} blocks)")
